# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7a09a9bae66eeeb8e5d3d1878562715ed6d164db89c1938b1f1e7b9c06a3b3a320244b6795450a9ce7eef97fb89e2d1ffbbe2cb5059c4604848a71e8ffee746

test:
  secret_key_base: 283b6f8d8454da3693c34269052b0bdbadd539d494d88bb85b537dcfcc826206719a97ff87f7504066af73344c622c6986fbd42e1beca301cea627b2a1df1d43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
